version: '2'
services:
  react-boilerplate-testing:
    ports:
      - '3333:3333'
    volumes:
      - ./:/app
    command: tail -f /dev/null
    build:
      dockerfile: _docker/react-boilerplate-testing/Dockerfile.devel
      context: .

